// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xssfunqmmlmpunhmhkzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzc2Z1bnFtbWxtcHVuaG1oa3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjM0NDgsImV4cCI6MjA2MzkzOTQ0OH0.q7PHxWYzj_1h7g6WKrAb_pz2cAnQ9dGKiE_Dm2cWE6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);