// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqvcafxlacamwkedbuxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdmNhZnhsYWNhbXdrZWRidXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTU1NzYsImV4cCI6MjA1ODY5MTU3Nn0.pkup1Ytx2SDSLoln0GvZuxW0-4jyx7CBjo2TZK6DVhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);